### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'dtype'

### ISSUE THREAD

**Issue by bayismet** [CVxTz/recommender_transformer#3]
Hello there!

I cloned the repo, downloaded the dataset  and tried to run "run.sh" with my own data path. This error comes up in Powershell and I have no idea why. Do I need to change anything else from cloned repo?

Thanks! 

PS D:\workspaces\recommender_transformer> python recommender/training.py --data_csv_path D:/workspaces/recommender_transformer/ml-25m/ratings.csv
len(train_data) 162541
len(val_data) 162541
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2021-10-04 02:29:58.691024: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll

  | Name                | Type               | Params
-----------------------------------------------------------
0 | item_embeddings     | Embedding          | 7.6 M
1 | input_pos_embedding | Embedding          | 65.5 K
2 | encoder             | TransformerEncoder | 3.6 M
3 | linear_out          | Linear             | 7.6 M
4 | do                  | Dropout            | 0
-----------------------------------------------------------
18.8 M    Trainable params
0         Non-trainable params
18.8 M    Total params
75.197    Total estimated model params size (MB)
Validation sanity check:  50%|████████████████████████████████████████████████████████████████████████████████████████                                                                                        | 1/2 [00:14<00:14, 14.60s/it]Traceback (most recent call last):
  File "D:\workspaces\recommender_transformer\recommender\training.py", line 156, in <module>
    train(
  File "D:\workspaces\recommender_transformer\recommender\training.py", line 134, in train
    trainer.fit(model, train_loader, val_loader)
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "C:\Python39\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Python39\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 93, in advance
    batch_idx, batch = next(dataloader_iter)
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "C:\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Python39\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'

**Comment by aarnavg17** [comment]
Could you solve this yet?

**Comment by bayismet** [comment]
Wow, it has been a full year and more. I remember we just switched to something else, but couldn't resolve this problem.

**Comment by aarnavg17** [comment]
Can you recommend what you switched to?

**Comment by CVxTz** [comment]
Hello,
I tried running the exact same code today and I had no issues. My guess is that its maybe due to your own setup being windows based, or not having the exact same dependencies and python version ( I am using py38 btw).
Good luck and use Linux, windows sucks.
![image](https://user-images.githubusercontent.com/13545260/222554460-90024961-be6f-49f5-a007-cbb7de252860.png)
